CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Leituras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Temperatura" double precision NOT NULL,
    "Umidade" double precision NOT NULL,
    "LedLigado" boolean NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Leituras" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260330173841_MigracaoPostgres', '9.0.1');

COMMIT;

